# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f428a9a679ea2c6f8b4aaeb66f47adfbbff1f4a6d8ee0b5e9eb62ed46595936fd0686d050a4911cd757d8899dc2a32e3c849a75ea28e2d4216ab4993a1b0a421

test:
  secret_key_base: 9bbbc3fa7c2e30ffd1e2591f860df15aed57ac7e4de676648fa9d3df7bb934edc4ac7332706af072e9a70cb6c5621d22aff011df822ee1c7cd8920dba80240bb

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
